name: Publish

on:
  push:
    branches:
      - main

jobs:
  docs:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: setup workspace
        run: |
          pip install -r requirements.txt
          pip install git+https://${{ secrets.OPENPECHA_BOT_GH_TOKEN }}@github.com/OpenPechaBot/mkdocs-material-insiders-backup.git
          echo ${{ secrets.OPENPECHA_ORG_DOMAIN }} > "${GITHUB_WORKSPACE}/docs/CNAME"
          remote_repo="https://x-access-token:${GITHUB_TOKEN}@${GITHUB_DOMAIN:-"github.com"}/${GITHUB_REPOSITORY}.git"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.${GITHUB_DOMAIN:-"github.com"}"
          git remote rm origin
          git remote add origin "${remote_repo}"

      - name: deploy
        run: |
          mkdocs gh-deploy --force
